{{- if .Values.imagePullSecret.enable}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-image-pull-secret
  namespace: {{ .Values.namespace | default .Release.namespace }}
data:
  .dockerconfigjson:
    {{ .Values.secretFiles.htpasswd | b64enc }}
type: kubernetes.io/dockerconfigjson
{{- end }}
